/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentrecord;

/**
 *
 * @author Daniella Penafiel
 */
public class AddSchedule extends javax.swing.JFrame {

    /**
     * Creates new form AddSchedule
     */
    public AddSchedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbEmployee = new javax.swing.JComboBox<>();
        btnaddschedule = new javax.swing.JButton();
        btn2recordgrade = new javax.swing.JButton();
        btnviewschedule = new javax.swing.JButton();
        btn2viewgrade = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btn2search = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btn2edit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbladdschedule = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtemployeeid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtcellnum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtbday = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt2status = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtdstarted = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtdresigned = new javax.swing.JTextField();
        btnviewgrades = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo (4).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -10, 420, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transparent.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, 80, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 29)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Record");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        cmbEmployee.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        cmbEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "College", "S.Y & Semester", "Course", "Student", "Employee", "Grades" }));
        cmbEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 160, 30));

        btnaddschedule.setBackground(new java.awt.Color(0, 0, 69));
        btnaddschedule.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnaddschedule.setForeground(new java.awt.Color(255, 255, 255));
        btnaddschedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (2).png"))); // NOI18N
        btnaddschedule.setText("Add Schedule");
        btnaddschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddscheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddschedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 160, -1));

        btn2recordgrade.setBackground(new java.awt.Color(0, 0, 69));
        btn2recordgrade.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btn2recordgrade.setForeground(new java.awt.Color(255, 255, 255));
        btn2recordgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit (3).png"))); // NOI18N
        btn2recordgrade.setText("Record Grade");
        btn2recordgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2recordgradeActionPerformed(evt);
            }
        });
        getContentPane().add(btn2recordgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 160, -1));

        btnviewschedule.setBackground(new java.awt.Color(0, 0, 69));
        btnviewschedule.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnviewschedule.setForeground(new java.awt.Color(255, 255, 255));
        btnviewschedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view (1).png"))); // NOI18N
        btnviewschedule.setText("View Schedule");
        btnviewschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewscheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btnviewschedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 160, -1));

        btn2viewgrade.setBackground(new java.awt.Color(0, 0, 69));
        btn2viewgrade.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btn2viewgrade.setForeground(new java.awt.Color(255, 255, 255));
        btn2viewgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eye.png"))); // NOI18N
        btn2viewgrade.setText("View Grades");
        btn2viewgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2viewgradeActionPerformed(evt);
            }
        });
        getContentPane().add(btn2viewgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 160, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 69));
        jLabel5.setText("Add Schedule");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setText("Search:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        txtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 230, 40));

        btn2search.setBackground(new java.awt.Color(0, 0, 69));
        btn2search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btn2search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn2search, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 80, 40));

        btnadd.setBackground(new java.awt.Color(0, 0, 69));
        btnadd.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (1).png"))); // NOI18N
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 130, -1));

        btn2edit.setBackground(new java.awt.Color(0, 0, 69));
        btn2edit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn2edit.setForeground(new java.awt.Color(255, 255, 255));
        btn2edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editing.png"))); // NOI18N
        btn2edit.setText("EDIT");
        getContentPane().add(btn2edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 210, 130, 40));

        btndelete.setBackground(new java.awt.Color(0, 0, 69));
        btndelete.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 210, 130, 40));

        tbladdschedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbladdschedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbladdscheduleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbladdschedule);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 860, 460));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel6.setText("School Year:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        txtemployeeid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtemployeeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemployeeidActionPerformed(evt);
            }
        });
        getContentPane().add(txtemployeeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel8.setText("Semester:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        txtlastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 180, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel10.setText("College Code :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        txtfirstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 180, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel12.setText("Block NO. :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        txtemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 180, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel13.setText("Subject Code:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        txtgender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });
        getContentPane().add(txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 180, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel14.setText("Day:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        txtcellnum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcellnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcellnumActionPerformed(evt);
            }
        });
        getContentPane().add(txtcellnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 180, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel7.setText("Time:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        txtaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        getContentPane().add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 180, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel15.setText("Room:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        txtbday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtbday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbdayActionPerformed(evt);
            }
        });
        getContentPane().add(txtbday, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 180, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel16.setText("Type:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        txt2status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt2status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2statusActionPerformed(evt);
            }
        });
        getContentPane().add(txt2status, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 180, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel17.setText("Sequence NO. :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        txtdstarted.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtdstarted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdstartedActionPerformed(evt);
            }
        });
        getContentPane().add(txtdstarted, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 180, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel18.setText("Employee ID:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, -1, -1));

        txtdresigned.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtdresigned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdresignedActionPerformed(evt);
            }
        });
        getContentPane().add(txtdresigned, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 180, 30));

        btnviewgrades.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnviewgrades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Beige and Black Minimalistic Modern Fashion Sale Blog Banner (3639 x 2138 px) (1360 x 730 px) (1).png"))); // NOI18N
        getContentPane().add(btnviewgrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        resfresh();
        
    }//GEN-LAST:event_formWindowActivated

    private void cmbEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEmployeeActionPerformed

    private void btnaddscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddscheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddscheduleActionPerformed

    private void btn2recordgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2recordgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2recordgradeActionPerformed

    private void btnviewscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewscheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewscheduleActionPerformed

    private void btn2viewgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2viewgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2viewgradeActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btn2searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2searchActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tbladdscheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbladdscheduleMouseClicked
        // TODO add your handling code here:
        int row = tbladdschedule.getSelectedRow();
    }//GEN-LAST:event_tbladdscheduleMouseClicked

    private void txtemployeeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemployeeidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemployeeidActionPerformed

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void txtcellnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcellnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcellnumActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtbdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbdayActionPerformed

    private void txt2statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2statusActionPerformed

    private void txtdstartedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdstartedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdstartedActionPerformed

    private void txtdresignedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdresignedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdresignedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2edit;
    private javax.swing.JButton btn2recordgrade;
    private javax.swing.JButton btn2search;
    private javax.swing.JButton btn2viewgrade;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnaddschedule;
    private javax.swing.JButton btndelete;
    private javax.swing.JLabel btnviewgrades;
    private javax.swing.JButton btnviewschedule;
    private javax.swing.JComboBox<String> cmbEmployee;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbladdschedule;
    private javax.swing.JTextField txt2status;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtbday;
    private javax.swing.JTextField txtcellnum;
    private javax.swing.JTextField txtdresigned;
    private javax.swing.JTextField txtdstarted;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtemployeeid;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtlastname;
    // End of variables declaration//GEN-END:variables
}
