/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentrecord;

import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.text.ParseException;
import java.text.SimpleDateFormat;


/**
 *
 * @author Charliz Dana
 */
public class Dashboard extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }
    public void refresh(){
        try {
            conn = ConnectDb.Connect();
            ps = conn.prepareStatement("SELECT*FROM studentRecord.COLLEGE ORDER BY COLLEGE_CODE");
            rs = ps.executeQuery();
            tblcollege.setModel(DbUtils.resultSetToTableModel(rs));
            
            tblcollege.getColumnModel().getColumn(0).setPreferredWidth(300);
            tblcollege.getColumnModel().getColumn(1).setPreferredWidth(300);
            tblcollege.getColumnModel().getColumn(2).setPreferredWidth(300);
            tblcollege.getColumnModel().getColumn(3).setPreferredWidth(300);
            tblcollege.getColumnModel().getColumn(4).setPreferredWidth(300);
            tblcollege.getColumnModel().getColumn(5).setPreferredWidth(300);
            tblcollege.getColumnModel().getColumn(6).setPreferredWidth(300);
            tblcollege.getColumnModel().getColumn(7).setPreferredWidth(300);
            tblcollege.getColumnModel().getColumn(8).setPreferredWidth(300);
            tblcollege.getColumnModel().getColumn(9).setPreferredWidth(300);
            tblcollege.getColumnModel().getColumn(10).setPreferredWidth(300);
        
            }catch (Exception e){
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcollege = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JTextField();
        txtdateopened = new javax.swing.JTextField();
        txtdateclosed = new javax.swing.JTextField();
        txtdescription = new javax.swing.JTextField();
        txtcollegecode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnrecordgrade = new javax.swing.JButton();
        btnaddschedule = new javax.swing.JButton();
        btnviewgrade = new javax.swing.JButton();
        btnviewschedule = new javax.swing.JButton();
        cmbcollege = new javax.swing.JComboBox<>();
        btnviewgrades = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsearch.setBackground(new java.awt.Color(0, 0, 69));
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 80, 40));

        tblcollege.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblcollege.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcollegeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcollege);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 950, -1));

        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 230, 40));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setText("Search:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        txtstatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstatusActionPerformed(evt);
            }
        });
        getContentPane().add(txtstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 190, 30));

        txtdateopened.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtdateopened.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateopenedActionPerformed(evt);
            }
        });
        getContentPane().add(txtdateopened, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 190, 30));

        txtdateclosed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtdateclosed, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 190, 30));

        txtdescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtdescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 190, 30));

        txtcollegecode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcollegecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcollegecodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtcollegecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 190, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel10.setText("Status:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel9.setText("Date Opened:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel8.setText("Date Closed:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel7.setText("Description:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel6.setText("College Code:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 69));
        jLabel5.setText("College");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 29)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Record");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo (4).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -10, 420, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transparent.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, 80, -1));

        btnadd.setBackground(new java.awt.Color(0, 0, 69));
        btnadd.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (1).png"))); // NOI18N
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 130, -1));

        btnedit.setBackground(new java.awt.Color(0, 0, 69));
        btnedit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editing.png"))); // NOI18N
        btnedit.setText("EDIT");
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 210, 130, 40));

        btndelete.setBackground(new java.awt.Color(0, 0, 69));
        btndelete.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 210, 130, 40));

        btnrecordgrade.setBackground(new java.awt.Color(0, 0, 69));
        btnrecordgrade.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnrecordgrade.setForeground(new java.awt.Color(255, 255, 255));
        btnrecordgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit (3).png"))); // NOI18N
        btnrecordgrade.setText("Record Grade");
        btnrecordgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecordgradeActionPerformed(evt);
            }
        });
        getContentPane().add(btnrecordgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 160, -1));

        btnaddschedule.setBackground(new java.awt.Color(0, 0, 69));
        btnaddschedule.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnaddschedule.setForeground(new java.awt.Color(255, 255, 255));
        btnaddschedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (2).png"))); // NOI18N
        btnaddschedule.setText("Add Schedule");
        btnaddschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddscheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddschedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 160, -1));

        btnviewgrade.setBackground(new java.awt.Color(0, 0, 69));
        btnviewgrade.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnviewgrade.setForeground(new java.awt.Color(255, 255, 255));
        btnviewgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eye.png"))); // NOI18N
        btnviewgrade.setText("View Grades");
        btnviewgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewgradeActionPerformed(evt);
            }
        });
        getContentPane().add(btnviewgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 160, -1));

        btnviewschedule.setBackground(new java.awt.Color(0, 0, 69));
        btnviewschedule.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnviewschedule.setForeground(new java.awt.Color(255, 255, 255));
        btnviewschedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view (1).png"))); // NOI18N
        btnviewschedule.setText("View Schedule");
        btnviewschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewscheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btnviewschedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 160, -1));

        cmbcollege.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        cmbcollege.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "College", "S.Y & Semester", "Course", "Subject", "Student", "Employee" }));
        cmbcollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcollegeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbcollege, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 160, 30));

        btnviewgrades.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnviewgrades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Beige and Black Minimalistic Modern Fashion Sale Blog Banner (3639 x 2138 px) (1360 x 730 px) (1).png"))); // NOI18N
        btnviewgrades.setText("jLabel1");
        getContentPane().add(btnviewgrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -70, 1360, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcollegecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcollegecodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcollegecodeActionPerformed

    private void txtdateopenedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateopenedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateopenedActionPerformed

    private void txtstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatusActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnaddscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddscheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddscheduleActionPerformed

    private void btnrecordgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecordgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrecordgradeActionPerformed

    private void btnviewscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewscheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewscheduleActionPerformed

    private void btnviewgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewgradeActionPerformed

    private void cmbcollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcollegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcollegeActionPerformed

    private void tblcollegeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcollegeMouseClicked
        // TODO add your handling code here:
        int row = tblcollege.getSelectedRow();

    }//GEN-LAST:event_tblcollegeMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnaddschedule;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnrecordgrade;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnviewgrade;
    private javax.swing.JLabel btnviewgrades;
    private javax.swing.JButton btnviewschedule;
    private javax.swing.JComboBox<String> cmbcollege;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search;
    private javax.swing.JTable tblcollege;
    private javax.swing.JTextField txtcollegecode;
    private javax.swing.JTextField txtdateclosed;
    private javax.swing.JTextField txtdateopened;
    private javax.swing.JTextField txtdescription;
    private javax.swing.JTextField txtstatus;
    // End of variables declaration//GEN-END:variables
}
