/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentrecord;

/**
 *
 * @author Daniella Penafiel
 */
public class Schoolyear_Semester extends javax.swing.JFrame {

    /**
     * Creates new form Schoolyear_Semester
     */
    public Schoolyear_Semester() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtstatus = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbcollege = new javax.swing.JComboBox<>();
        btnaddschedule = new javax.swing.JButton();
        btnrecordgrade = new javax.swing.JButton();
        btnviewschedule = new javax.swing.JButton();
        btnviewgrade = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcollege = new javax.swing.JTable();
        txtcollegecode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        search1 = new javax.swing.JTextField();
        btnsearch1 = new javax.swing.JButton();
        btnadd1 = new javax.swing.JButton();
        btnedit1 = new javax.swing.JButton();
        btndelete1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblcollege1 = new javax.swing.JTable();
        btnviewgrades1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtstatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstatusActionPerformed(evt);
            }
        });
        getContentPane().add(txtstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 400, 190, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel13.setText("Semester:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 370, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo (4).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -10, 420, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transparent.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, 80, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 29)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Record");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        cmbcollege.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        cmbcollege.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S.Y & Semester", "College", "S.Y & Semester", "Course", "Student", "Employee", "Grades" }));
        cmbcollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcollegeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbcollege, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 160, 30));

        btnaddschedule.setBackground(new java.awt.Color(0, 0, 69));
        btnaddschedule.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnaddschedule.setForeground(new java.awt.Color(255, 255, 255));
        btnaddschedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (2).png"))); // NOI18N
        btnaddschedule.setText("Add Schedule");
        btnaddschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddscheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddschedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 160, -1));

        btnrecordgrade.setBackground(new java.awt.Color(0, 0, 69));
        btnrecordgrade.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnrecordgrade.setForeground(new java.awt.Color(255, 255, 255));
        btnrecordgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit (3).png"))); // NOI18N
        btnrecordgrade.setText("Record Grade");
        btnrecordgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecordgradeActionPerformed(evt);
            }
        });
        getContentPane().add(btnrecordgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 160, -1));

        btnviewschedule.setBackground(new java.awt.Color(0, 0, 69));
        btnviewschedule.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnviewschedule.setForeground(new java.awt.Color(255, 255, 255));
        btnviewschedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view (1).png"))); // NOI18N
        btnviewschedule.setText("View Schedule");
        btnviewschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewscheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btnviewschedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 160, -1));

        btnviewgrade.setBackground(new java.awt.Color(0, 0, 69));
        btnviewgrade.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnviewgrade.setForeground(new java.awt.Color(255, 255, 255));
        btnviewgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eye.png"))); // NOI18N
        btnviewgrade.setText("View Grades");
        btnviewgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewgradeActionPerformed(evt);
            }
        });
        getContentPane().add(btnviewgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 160, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 69));
        jLabel5.setText("S.Y & Semester");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setText("Search:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 230, 40));

        btnsearch.setBackground(new java.awt.Color(0, 0, 69));
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 70, -1));

        btnadd.setBackground(new java.awt.Color(0, 0, 69));
        btnadd.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (1).png"))); // NOI18N
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 130, -1));

        btnedit.setBackground(new java.awt.Color(0, 0, 69));
        btnedit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editing.png"))); // NOI18N
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, 130, 40));

        btndelete.setBackground(new java.awt.Color(0, 0, 69));
        btndelete.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 670, 130, 40));

        tblcollege.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        tblcollege.setForeground(new java.awt.Color(0, 0, 69));
        tblcollege.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "School Year"
            }
        ));
        tblcollege.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcollegeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcollege);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 440, 380));

        txtcollegecode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcollegecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcollegecodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtcollegecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 190, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel6.setText("School Year:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel12.setText("Search:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        search1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        getContentPane().add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 230, 40));

        btnsearch1.setBackground(new java.awt.Color(0, 0, 69));
        btnsearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btnsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearch1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 230, 70, 40));

        btnadd1.setBackground(new java.awt.Color(0, 0, 69));
        btnadd1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnadd1.setForeground(new java.awt.Color(255, 255, 255));
        btnadd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (1).png"))); // NOI18N
        btnadd1.setText("ADD");
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 670, 130, -1));

        btnedit1.setBackground(new java.awt.Color(0, 0, 69));
        btnedit1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnedit1.setForeground(new java.awt.Color(255, 255, 255));
        btnedit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editing.png"))); // NOI18N
        btnedit1.setText("EDIT");
        getContentPane().add(btnedit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 670, 130, 40));

        btndelete1.setBackground(new java.awt.Color(0, 0, 69));
        btndelete1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btndelete1.setForeground(new java.awt.Color(255, 255, 255));
        btndelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        btndelete1.setText("DELETE");
        btndelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete1ActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 670, 130, 40));

        tblcollege1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semester"
            }
        ));
        tblcollege1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcollege1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblcollege1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 440, 380));

        btnviewgrades1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnviewgrades1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Beige and Black Minimalistic Modern Fashion Sale Blog Banner (3639 x 2138 px) (1360 x 730 px) (1).png"))); // NOI18N
        getContentPane().add(btnviewgrades1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -130, 1380, 990));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
          refresh();
    }//GEN-LAST:event_formWindowActivated

    private void cmbcollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcollegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcollegeActionPerformed

    private void btnaddscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddscheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddscheduleActionPerformed

    private void btnrecordgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecordgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrecordgradeActionPerformed

    private void btnviewscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewscheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewscheduleActionPerformed

    private void btnviewgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewgradeActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tblcollegeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcollegeMouseClicked
        // TODO add your handling code here:
        int row = tblcollege.getSelectedRow();
    }//GEN-LAST:event_tblcollegeMouseClicked

    private void txtcollegecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcollegecodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcollegecodeActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1ActionPerformed

    private void btnsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearch1ActionPerformed

    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnadd1ActionPerformed

    private void btndelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndelete1ActionPerformed

    private void tblcollege1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcollege1MouseClicked
        // TODO add your handling code here:
        int row = tblcollege.getSelectedRow();
    }//GEN-LAST:event_tblcollege1MouseClicked

    private void txtstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatusActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Schoolyear_Semester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Schoolyear_Semester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Schoolyear_Semester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Schoolyear_Semester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Schoolyear_Semester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnadd1;
    private javax.swing.JButton btnaddschedule;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndelete1;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnedit1;
    private javax.swing.JButton btnrecordgrade;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsearch1;
    private javax.swing.JButton btnviewgrade;
    private javax.swing.JLabel btnviewgrades1;
    private javax.swing.JButton btnviewschedule;
    private javax.swing.JComboBox<String> cmbcollege;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField search;
    private javax.swing.JTextField search1;
    private javax.swing.JTable tblcollege;
    private javax.swing.JTable tblcollege1;
    private javax.swing.JTextField txtcollegecode;
    private javax.swing.JTextField txtstatus;
    // End of variables declaration//GEN-END:variables
}
