/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentrecord;

/**
 *
 * @author Daniella Penafiel
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbcollege = new javax.swing.JComboBox<>();
        btn4addschedule = new javax.swing.JButton();
        btn4recordgrade = new javax.swing.JButton();
        btn4viewschedule = new javax.swing.JButton();
        btn4viewgrade = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btn4add = new javax.swing.JButton();
        btn4edit = new javax.swing.JButton();
        btn4delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstudent = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtemployeeid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtcellnum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtbday = new javax.swing.JTextField();
        txt2status = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtdresigned = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtdstarted = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtcellnum1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnviewgrades1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transparent.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transparent.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, 80, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 29)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Record");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        cmbcollege.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        cmbcollege.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S.Y & Semester", "College", "S.Y & Semester", "Course", "Student", "Employee", "Grades" }));
        cmbcollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcollegeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbcollege, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 160, 30));

        btn4addschedule.setBackground(new java.awt.Color(0, 0, 69));
        btn4addschedule.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btn4addschedule.setForeground(new java.awt.Color(255, 255, 255));
        btn4addschedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (2).png"))); // NOI18N
        btn4addschedule.setText("Add Schedule");
        btn4addschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4addscheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btn4addschedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 160, -1));

        btn4recordgrade.setBackground(new java.awt.Color(0, 0, 69));
        btn4recordgrade.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btn4recordgrade.setForeground(new java.awt.Color(255, 255, 255));
        btn4recordgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit (3).png"))); // NOI18N
        btn4recordgrade.setText("Record Grade");
        btn4recordgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4recordgradeActionPerformed(evt);
            }
        });
        getContentPane().add(btn4recordgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 160, -1));

        btn4viewschedule.setBackground(new java.awt.Color(0, 0, 69));
        btn4viewschedule.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btn4viewschedule.setForeground(new java.awt.Color(255, 255, 255));
        btn4viewschedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view (1).png"))); // NOI18N
        btn4viewschedule.setText("View Schedule");
        btn4viewschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4viewscheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btn4viewschedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 160, -1));

        btn4viewgrade.setBackground(new java.awt.Color(0, 0, 69));
        btn4viewgrade.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btn4viewgrade.setForeground(new java.awt.Color(255, 255, 255));
        btn4viewgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eye.png"))); // NOI18N
        btn4viewgrade.setText("View Grades");
        btn4viewgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4viewgradeActionPerformed(evt);
            }
        });
        getContentPane().add(btn4viewgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 160, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 69));
        jLabel5.setText("Student");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setText("Search:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 230, 40));

        btnsearch.setBackground(new java.awt.Color(0, 0, 69));
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 80, 40));

        btn4add.setBackground(new java.awt.Color(0, 0, 69));
        btn4add.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn4add.setForeground(new java.awt.Color(255, 255, 255));
        btn4add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (1).png"))); // NOI18N
        btn4add.setText("ADD");
        btn4add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4addActionPerformed(evt);
            }
        });
        getContentPane().add(btn4add, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 130, -1));

        btn4edit.setBackground(new java.awt.Color(0, 0, 69));
        btn4edit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn4edit.setForeground(new java.awt.Color(255, 255, 255));
        btn4edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editing.png"))); // NOI18N
        btn4edit.setText("EDIT");
        getContentPane().add(btn4edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 210, 130, 40));

        btn4delete.setBackground(new java.awt.Color(0, 0, 69));
        btn4delete.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn4delete.setForeground(new java.awt.Color(255, 255, 255));
        btn4delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        btn4delete.setText("DELETE");
        btn4delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn4delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 210, 130, 40));

        tblstudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student_No", "Last_Name", "First_Name", "Email", "Gender", "Course_Code", "CP_Num", "Address", "Birthday", "Status", "Date_Started", "Date_Graduated"
            }
        ));
        tblstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblstudent);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 910, 440));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel6.setText("Student No. :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        txtemployeeid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtemployeeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemployeeidActionPerformed(evt);
            }
        });
        getContentPane().add(txtemployeeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel8.setText("Last Name :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        txtlastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 180, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel10.setText("First Name :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        txtfirstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 180, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel12.setText("Email : ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        txtemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 180, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel13.setText("Gender :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        txtgender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });
        getContentPane().add(txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 180, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel14.setText("Date Graduated:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, -1, -1));

        txtcellnum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcellnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcellnumActionPerformed(evt);
            }
        });
        getContentPane().add(txtcellnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 180, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel7.setText("Cell Number:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        txtbday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtbday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbdayActionPerformed(evt);
            }
        });
        getContentPane().add(txtbday, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 180, 30));

        txt2status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt2status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2statusActionPerformed(evt);
            }
        });
        getContentPane().add(txt2status, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 180, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel17.setText("Status:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        txtdresigned.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtdresigned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdresignedActionPerformed(evt);
            }
        });
        getContentPane().add(txtdresigned, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 180, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel18.setText("Date Started:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, -1, -1));

        txtdstarted.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtdstarted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdstartedActionPerformed(evt);
            }
        });
        getContentPane().add(txtdstarted, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 180, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel16.setText("Birthday:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel15.setText("Address:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        txtaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        getContentPane().add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 180, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel19.setText("Course Code:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        txtcellnum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcellnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcellnum1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtcellnum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 180, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo (4).png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -10, 420, 90));

        btnviewgrades1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnviewgrades1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Beige and Black Minimalistic Modern Fashion Sale Blog Banner (3639 x 2138 px) (1360 x 730 px) (1).png"))); // NOI18N
        getContentPane().add(btnviewgrades1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_formWindowActivated

    private void cmbcollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcollegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcollegeActionPerformed

    private void btn4addscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4addscheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4addscheduleActionPerformed

    private void btn4recordgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4recordgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4recordgradeActionPerformed

    private void btn4viewscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4viewscheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4viewscheduleActionPerformed

    private void btn4viewgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4viewgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4viewgradeActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btn4addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4addActionPerformed

    private void btn4deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4deleteActionPerformed

    private void tblstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstudentMouseClicked
        // TODO add your handling code here:
        int row = tblstudent.getSelectedRow();
    }//GEN-LAST:event_tblstudentMouseClicked

    private void txtemployeeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemployeeidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemployeeidActionPerformed

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void txtcellnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcellnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcellnumActionPerformed

    private void txtbdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbdayActionPerformed

    private void txt2statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2statusActionPerformed

    private void txtdresignedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdresignedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdresignedActionPerformed

    private void txtdstartedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdstartedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdstartedActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtcellnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcellnum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcellnum1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn4add;
    private javax.swing.JButton btn4addschedule;
    private javax.swing.JButton btn4delete;
    private javax.swing.JButton btn4edit;
    private javax.swing.JButton btn4recordgrade;
    private javax.swing.JButton btn4viewgrade;
    private javax.swing.JButton btn4viewschedule;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel btnviewgrades1;
    private javax.swing.JComboBox<String> cmbcollege;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search;
    private javax.swing.JTable tblstudent;
    private javax.swing.JTextField txt2status;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtbday;
    private javax.swing.JTextField txtcellnum;
    private javax.swing.JTextField txtcellnum1;
    private javax.swing.JTextField txtdresigned;
    private javax.swing.JTextField txtdstarted;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtemployeeid;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtlastname;
    // End of variables declaration//GEN-END:variables
}
