/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentrecord;

/**
 *
 * @author Daniella Penafiel
 */
public class ViewGrades extends javax.swing.JFrame {

    /**
     * Creates new form ViewGrades
     */
    public ViewGrades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbcollege = new javax.swing.JComboBox<>();
        btn4addschedule = new javax.swing.JButton();
        btn4recordgrade = new javax.swing.JButton();
        btn4viewschedule = new javax.swing.JButton();
        btn4viewgrade = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblviewgrades = new javax.swing.JTable();
        viewschedbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo (4).png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -10, 420, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transparent.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, 80, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 29)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Record");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        cmbcollege.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        cmbcollege.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S.Y & Semester", "College", "S.Y & Semester", "Course", "Student", "Employee", "Grades" }));
        cmbcollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcollegeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbcollege, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 160, 30));

        btn4addschedule.setBackground(new java.awt.Color(0, 0, 69));
        btn4addschedule.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btn4addschedule.setForeground(new java.awt.Color(255, 255, 255));
        btn4addschedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add (2).png"))); // NOI18N
        btn4addschedule.setText("Add Schedule");
        btn4addschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4addscheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btn4addschedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 160, -1));

        btn4recordgrade.setBackground(new java.awt.Color(0, 0, 69));
        btn4recordgrade.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btn4recordgrade.setForeground(new java.awt.Color(255, 255, 255));
        btn4recordgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit (3).png"))); // NOI18N
        btn4recordgrade.setText("Record Grade");
        btn4recordgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4recordgradeActionPerformed(evt);
            }
        });
        getContentPane().add(btn4recordgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 160, -1));

        btn4viewschedule.setBackground(new java.awt.Color(0, 0, 69));
        btn4viewschedule.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btn4viewschedule.setForeground(new java.awt.Color(255, 255, 255));
        btn4viewschedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view (1).png"))); // NOI18N
        btn4viewschedule.setText("View Schedule");
        btn4viewschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4viewscheduleActionPerformed(evt);
            }
        });
        getContentPane().add(btn4viewschedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 160, -1));

        btn4viewgrade.setBackground(new java.awt.Color(0, 0, 69));
        btn4viewgrade.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btn4viewgrade.setForeground(new java.awt.Color(255, 255, 255));
        btn4viewgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eye.png"))); // NOI18N
        btn4viewgrade.setText("View Grades");
        btn4viewgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4viewgradeActionPerformed(evt);
            }
        });
        getContentPane().add(btn4viewgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 160, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 69));
        jLabel6.setText("View Grade");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        tblviewgrades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "row", "row 2", "row 3", "row 4", "row 5", "row 6", "row 7", "row 8"
            }
        ));
        tblviewgrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblviewgradesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblviewgrades);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 1060, 450));

        viewschedbg.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        viewschedbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Beige and Black Minimalistic Modern Fashion Sale Blog Banner (3639 x 2138 px) (1360 x 730 px) (1).png"))); // NOI18N
        getContentPane().add(viewschedbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        resfresh();
        
    }//GEN-LAST:event_formWindowActivated

    private void cmbcollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcollegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcollegeActionPerformed

    private void btn4addscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4addscheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4addscheduleActionPerformed

    private void btn4recordgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4recordgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4recordgradeActionPerformed

    private void btn4viewscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4viewscheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4viewscheduleActionPerformed

    private void btn4viewgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4viewgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4viewgradeActionPerformed

    private void tblviewgradesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblviewgradesMouseClicked
        // TODO add your handling code here:
        int row = tblviewgrades.getSelectedRow();
    }//GEN-LAST:event_tblviewgradesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn4addschedule;
    private javax.swing.JButton btn4recordgrade;
    private javax.swing.JButton btn4viewgrade;
    private javax.swing.JButton btn4viewschedule;
    private javax.swing.JComboBox<String> cmbcollege;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblviewgrades;
    private javax.swing.JLabel viewschedbg;
    // End of variables declaration//GEN-END:variables
}
